"""empty message

Revision ID: 74a970fb00c9
Revises: 1c3f6c5c4802
Create Date: 2022-11-06 17:56:53.809515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a970fb00c9'
down_revision = '1c3f6c5c4802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbu_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gbu_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dbu_logs')
    # ### end Alembic commands ###
